services:
  Brand.infrastructure.BrandSchema:
    class: ../../../Contexts/Brand/infrastructure/Sequelize/BrandSchema
    arguments: ['@Shared.SequelizeConfig']
    method: createModel

  Brand.infrastructure.SequelizeBrandRepository:
    class: ../../../Contexts/Brand/infrastructure/Sequelize/SequelizeBrandRepository
    arguments: ['@Shared.RedisConfig']

  Brand.application.BrandCreator: 
    class: ../../../Contexts/Brand/application/BrandCreator
    argument: ['@Brand.infrastructure.SequelizeBrandRepository']
    
  Brand.application.BrandFinder: 
    class: ../../../Contexts/Brand/application/BrandFInder
    argument: ['@Brand.infrastructure.SequelizeBrandRepository']

  Brand.application.BrandFinderAll: 
    class: ../../../Contexts/Brand/application/BrandFinderAll
    argument: ['@Brand.infrastructure.SequelizeBrandRepository']

  Brand.application.BrandUpadater: 
    class: ../../../Contexts/Brand/application/BrandUpadater
    argument: ['@Brand.infrastructure.SequelizeBrandRepository']
