const unidadList = [
	'Auditoria Interna',
	'Coord Recaudación Gobernaciones Alcaldias y Otros',
	'Coord Recaudación Seniat',
	'Coord Reclamos de Canales Electrónicos Tdc Zona 2',
	'Coord Reclamos de Canales Electrónicos Tdd Zona 1',
	'Gerencia de Area Proyect de Integrac de Plataforma',
	'Coord Reclamos de Canales Electrónicos Tdd Zona 2',
	'Coord Reclamos de Canales Eletrónicos Tdc Zona 1',
	'Coord Serv Al Clt y Procesamiento de Solicitudes',
	'Coord. (centro - los Llanos)',
	'Coord. (occidente - Andes)',
	'V.P.E. de Banca Corporativa',
	'Coord. Atención Interna Cai Capital',
	'Coord. Atención Interna Cai Occidente',
	'Coord. Atención Telefónica Al Cliente (m) I',
	'Gerencia de Negocios Oriente (bei)',
	'Coord. Atención Telefónica Al Cliente (m) II',
	'Coord. Atención Telefónica Al Cliente (n) V',
	'Coord. Atención Telefónica Al Cliente (n) VI',
	'Coord. Atención Telefónica Al Cliente (t) III',
	'Coord. Atención Telefónica Al Cliente (t) IV',
	'V.P. Banca de Relación',
	'V.P.E. de Operaciones y Administración',
	'Coord. Cobranza de Creditos Al Consumo',
	'Coord. Consola Torre Financiera',
	'V.P. de Zona II Administracion de Agencias II (adm)',
	'Coord. Correspondencia Capital',
	'Coord. Correspondencia Occidente',
	'Coord. Digitalización y Ctrol de Arch Aragua',
	'Coord. Digitalización y Ctrol de Arch Occidente I',
	'Coord. Digitalización y Ctrol de Arch Occidente II',
	'Coord. Digitalización y Ctrol de Arch. Capital',
	'V.P. Prevención y Control Lcftfpadm',
	'Coord. Fianzas, Garantías Internacionales',
	'Gerencia de Cumplimiento',
	'Coord. Fianzas, Garantías y Respaldo de Crédito',
	'Coord. Mantenimiento y Soporte Al Cliente',
	'Gerencia de Area Administración de Usuarios',
	'Coord. Registro de Clientes Región Capital',
	'Coord. Registro de Clientes Región Central',
	'V.P. Bei II',
	'Coord. Registro de Clientes Región Occidente',
	'V.P. Regional Gestión Operativa de Agencias',
	'Coord. Seguimiento y Control de Crédito',
	'Coord. Seguridad Almacenes Guatire',
	'Coord. Seguridad Física Región Capital',
	'Coord. Seguridad San Bernardino',
	'Coord. Soluciones Integrales Whatsapp',
	'Coordinación Agencia Móvil',
	'Coordinación Almacén y Proveeduría (caracas)',
	'Coordinación Almacén y Proveeduría (occidente)',
	'Coordinación Arquitectura',
	'Coordinación Atención Al Accionista',
	'V.P. Gestión de Negocios',
	'Coordinación Atención Al Cliente',
	'Coordinación Atención Onboarding Bnc',
	'Coordinación Capacitación',
	'Coordinación Centro Alterno',
	'Coordinación Compensación Suiche 7b',
	'Coordinación Compensación y Procesos Contables',
	'Coordinación Comunicaciones Internas',
	'Gerencia de Negocios Capital (bei) II',
	'Coordinación Cont Operativo de Centros de Acopio',
	'Coordinación Contabilidad',
	'Coordinación Contabilidad Canales Electrónicos',
	'Gerencia Asuntos Corp. y Confirmaciones Bancarias',
	'V.P. de Negocios Zona Ia',
	'Gerencia de Innovación y Productos',
	'Gerencia de Area de Negocios Corporativa I',
	'Coordinación Control Adm. y Centros de Acopio',
	'Gerencia de Área Back Office Registro de Cliente (adm)',
	'Coordinación Control de Inventario',
	'Coordinación Control y Seguimiento',
	'Coordinación Ctrol, Registro de Op y Papel Valor',
	'Coordinación Cultura',
	'Coordinación Cumplimiento Normativo',
	'Coordinación Cumplimiento Tributario Estadal',
	'Coordinación Cumplimiento Tributario Municipal',
	'Gerencia de Area de Negocios Telecomunicaciones',
	'Coordinación Custodia Documental',
	'Coordinación Custodia Títulos Valores',
	'Coordinación Custodios y Sistemas de Seguridad',
	'Coordinación de Atención Post Venta',
	'Coordinación de Beneficios',
	'Coordinación de Compras',
	'Coordinación de Contratos',
	'V.P. Bei I',
	'Coordinación de Emprendedores',
	'Coordinación de Formación',
	'Gcia. de Analisis de Credito Banca Corporativa',
	'Coordinación de Ivss, Nómina y Domiciliaciones',
	'Gerencia de Area Sistema Distribuido',
	'Gerencia Servicios Post Venta Jurídicos',
	'Coordinación de Logística Moneda Nacional',
	'Coordinación de Procesos Especiales',
	'Coordinación de Productos',
	'Coordinación de Proveedores',
	'Coordinación de Proyectos y Soporte Técnico',
	'Gerencia de Administración Acceso Identidad',
	'Coordinacion de Reportería',
	'Coordinación de Servicios',
	'Coordinación de Servicios Generales',
	'Gerencia de Área de Comunicaciones Corporativas',
	'Coordinación de Transporte',
	'Coordinación Desarrollo de Canales Digitales',
	'Coordinación Diseño Gráfico',
	'Coordinación Documentación de Crédito',
	'Coordinación Domiciliación Pos',
	'Coordinación Eventos E Imagen Corporativas',
	'Coordinacion Gestion de Personal',
	'Coordinación Gestión Operativa de Zonas',
	'Coordinación Gestión y Traslado de Activos',
	'Coordinación Información Financiera',
	'Coordinación Inspección',
	'Coordinación Inteligencia de Negocios',
	'Coordinación Interbancario Nacional',
	'Coordinación Investigaciones Caracas',
	'Coordinación Investigaciones Maracaibo',
	'Coordinación Liberaciones',
	'Coordinación Marca',
	'Coordinación Medios Digitales',
	'Coordinación Moneda Extranjera',
	'Coordinación Occidente II',
	'Coordinacion Operaciones Accionarias',
	'Gerencia de Desarrollo de Canales Digitales',
	'Coordinación Operaciones Back Office y Seguro',
	'Coordinación Operaciones de Cambio',
	'Coord. Creditos Comerciales',
	'Coordinación Pago Proveedores',
	'Coordinación Producción Caracas',
	'Gerencia de Procesos Especiales y Reportería',
	'Coordinación Producción Occidente',
	'Coordinación Proyectos Técnicos',
	'Coordinación Recuperaciones Pos',
	'Coordinación Redes y Comunicaciones Caracas',
	'Coordinación Redes y Comunicaciones Occidente',
	'Coordinación Responsabilidad Social Corporativa',
	'Coordinación Revisoría',
	'Coordinación Servicio Al Cliente Pos',
	'Gerencia de Proyectos Ti',
	'Coordinación Servicios de Afiliación Pos',
	'Gerencia de Area Calidad y Cumplimiento',
	'Coordinación Soporte Pos Capital',
	'Gerencia de Control de Calidad',
	'Coordinación Soporte Pos Centro',
	'Coordinación Soporte Pos-occidente',
	'V.P. Bei III',
	'Coordinación Soporte Vip',
	'Coordinación Tarjetas y Medios de Pago',
	'Coordinación Unidad Móvil',
	'Coordinación Viáticos y Tributos',
	'Coordinación Zona Aragua',
	'Coordinación Zona Capital I',
	'Coordinación Zona Capital II',
	'Coordinación Zona Capital III',
	'Coordinación Zona Carabobo',
	'Coordinación Zona Insular',
	'Coordinación Zona los Llanos',
	'Coordinación Zona Occidente I',
	'Coordinaciónde Logística Moneda Extranjera',
	'Corrd. Seguridad Física Región Andes I',
	'Gerencia de Eficiencia Comercial',
	'Corrd. Seguridad Física Región Andes II',
	'Corrd. Seguridad Física Región Central',
	'Corrd. Seguridad Física Región Falcón',
	'Corrd. Seguridad Física Región Occidente',
	'Gcia. de Analisis de Credito Banca Comercial',
	'Corrd. Seguridad Física Región Oriente',
	'Coordinación Monitoreo Pos Caracas',
	'Defensoria del Cliente',
	'Gerencia Sistemas de Sucursales',
	'Gcia Análisis de Créd Banca Comercial (p-c-e)',
	'Gcia Análisis de Créd Banca Comercial (p-n)',
	'Gcia Análisis de Créd Banca Corporativa Multinac',
	'Gcia de Área Control de Activos Muebles',
	'Gcia de Área de Digitalizac, Ctrol Archi. y Corres',
	'Gcia de Área Desarrollo y Sostenibilidad',
	'Gcia de Área Estadisticas, Análisis Estr y Capacit',
	'Gcia de Area Gestión de Estructuras Direcc Central',
	'Gcia de Área Gestión Servicios Administrativos',
	'Gcia de Área Infraestructura y Mantenimiento Fisíco',
	'Gcia de Área Neg Multinacional Consumo y Manufactu',
	'Gcia de Área Pago Proveedores',
	'Gcia de Área Productos, Contratos Especiales y Cré',
	'Gcia de Mantenimiento Fisíco Sedes (caracas)',
	'Gcia de Mantenimiento Fisíco Sedes (occidente)',
	'Gcia Determinación y Declaración Tributaria E y M',
	'V.P. Prevención y Control del Fraude',
	'Gerencia de Negocios (bei) II',
	'Gcia Determinación y Declaración Tributaria N y P',
	'Gcia. de Análisis de Credito Región Occidente',
	'Gcia. de Área de Negocios Sector  Público Centro',
	'Gerencia de Área Compras y Servicios Generales',
	'Gcia. de Área Gestión Adm y Ctrol Op. de Agencias',
	'Gcia. de Área Gestión de Proyectos Estratégicos',
	'Gcia. de Área Planificación Estratégica y Control',
	'Gcia. de Control Estadistico E Informe Especiales',
	'Gerencia de Negocios (bei) I',
	'Gcia. de Negocios Sect Agropec Rg. Aragua-carabobo',
	'Gcia. de Negocios Sect Agropecuario Rg. Capital',
	'Gcia. de Negocios Sect Agropecuario Rg. Cent. Occi',
	'Gerencia de Área Planificación Financiera',
	'Gcia. Reg. Operacion de Agencias Aragua los Llanos',
	'Gerencia Activo Fijo',
	'Gerencia de Área Analisis de Gestión',
	'Gerencia Administración Bases de Datos',
	'Gerencia Afiliación Al Servicio Pos Interior',
	'Gerencia Afiliación Al Servicio Pos Metropolitana',
	'Gerencia Regional de Negocios Sector Público I',
	'Gerencia Análisis Estratégico y Detección de Tipol',
	'Gerencia Analítica Digital',
	'Gerencia Apoyo A Presidencia Ejecutiva',
	'Gerencia Asuntos Corp y Confirmaciones Bancarias',
	'Gerencia Banca en Línea',
	'Gerencia Centro de Acopio Maracaibo',
	'Gerencia Centro de Acopio Maracay',
	'Gerencia Centro de Acopio Valencia',
	'Gerencia Contabilidad',
	'Gerencia Control Financiero y Sucursal',
	'Gerencia Control Institucional',
	'Gerencia Control y Gestión',
	'Gerencia Control y Seguimiento',
	'V.P. Contratos y Servicios',
	'Gerencia de Admin de Cuentas Tdc',
	'Gerencia de Análisis de Operaciones Financieras',
	'Gerencia de Aplicaciones de Cobro y Proce Masivos',
	'Gerencia de Archivo Central de Credito',
	'Gerencia de Área Admin de Cuentas y Producción Tdc',
	'Gerencia de Area Admin. de Seguridad Bancaria',
	'Gerencia de Area Administración de Bases de Datos',
	'Gerencia de Área Agencia Móvil',
	'Gerencia de Área Almacen y Proveeduría',
	'Gerencia de Área Análisis y Supervisión de Op Fina',
	'Gerencia de Área Arquitectura de Procesos',
	'Gerencia de Área Arquitectura Ti',
	'Gerencia de Area Arquitectura y Proyectos de Seguridad',
	'V.P. Cumplimiento y Control',
	'Gerencia de Área Aseguramiento de Software',
	'Gerencia de Area Asuntos Regulatorios',
	'Gerencia de Área Asuntos Técnicos Regulatorios',
	'Gerencia de Area Auditoria de Sistemas',
	'Gerencia de Area Auditoria Financiera',
	'Gerencia de Área Back Office Registro de Cliente',
	'Gerencia de Área Canales y Procesos Contables',
	'Gerencia de Area Compensación y Beneficios',
	'V.P. de Zona I Administracion de Agencias (adm) I',
	'Gerencia de Área Compras y Servicios Genereales',
	'Gerencia de Área Contabilidad',
	'Gerencia de Area Contabilidad Fiduciaria',
	'Gerencia de Area Contact Center',
	'Gerencia de Desarrollo de Sistemas Internos',
	'Gerencia de Area Contratos y Proveedores',
	'Gerencia de Area Control de Cambios y Certififación',
	'Gerencia de Area Control de Gestión',
	'Gerencia de Area Control de Inmuebles Arrendados',
	'Gerencia de Área Control de Inmuebles Propios',
	'Gerencia de Documentación de Activos',
	'Gerencia de Área Control E Información Financiera',
	'Gerencia de Area Control Financiero',
	'Gerencia de Área Control Presupuestario',
	'V.P. Corporativa Bei Sector Público',
	'Gerencia de Area Core Bancario',
	'Gerencia de Área Corporativa Centro',
	'Gerencia de Area Corresponsalia',
	'Gerencia de Area Bi y Regulatorios',
	'Gerencia de Área Ctrl y Seguimiento de Auditoría',
	'Gerencia de Área Gestión de Estructuras Negocio',
	'Gerencia de Area de Contabilidad',
	'Gerencia de Área Ctrol Institucional y Asuntos Corp',
	'Gerencia de Área Cumplimiento Tributario',
	'V.P. de Gestión Operativa Interna y Proyectos Espe',
	'Gerencia de Area de Auditoria de Agencias',
	'V.P. Control de Activos',
	'Gerencia de Área de Cobranza y Recuperaciones',
	'Gerencia de Area de Comunicaciones',
	'Gerencia Digitalización, Ctrol Archiv. y Correspondencia',
	'Gerencia de Área Admin de Cuentas y Estadísticas',
	'Gerencia de Área de Contraloría de Datos',
	'Gerencia de Area Pago A Proveedores',
	'Gerencia de Área de Custodia y Operaciones Cambiarias',
	'Gerencia de Área de Liquidaciones y Aplic de Cobro',
	'Gerencia de Área de Negocios Internacionales',
	'Gerencia Oficina Digital',
	'Gerencia de Área de Negocios Sector Público',
	'V.P.E. Gestión de la Seguridad y Prevención',
	'Gerencia de Area de Soporte Pos',
	'Gerencia de Área de Infraestructura y Mantenimient',
	'Gerencia de Área de Transporte de Valores y Centros de Acopio',
	'Gerencia de Area Def. de Modelos de Calidad',
	'Gerencia de Área Desarrollo de Canales Digitales',
	'Gerencia de Área Desarrollo de Soluciones Digitale',
	'Gerencia de Área Emisión y Distribución',
	'Gerencia de Area Energía',
	'Gerencia de Área Legal de Créditos, Productos y Serv.',
	'Gerencia de Area Estrategia y Riesgo de Ciberseguridad',
	'Gerencia de Area Eval. de Indicadores de Calidad',
	'Gerencia de Área Experiencia Digital',
	'Gerencia de Area Formacion y Desarrollo',
	'Gerencia de Area Seguridad Informatica',
	'Gerencia de Área Gestión de Estructuras de Negocio',
	'Gerencia de Area Gestion de Servicios Al Personal',
	'Gerencia de Área Ingeniería de Datos',
	'Gerencia de Área Innovación y Productos',
	'V.P. Banca Corporativa',
	'Gerencia de Area Integración de Plataforma',
	'V.P. de Negocios Zona Iia',
	'Gerencia de Área Integración y Soporte de Sol Digi',
	'Gerencia de Área Legal de Créditos',
	'Gerencia de Área Legal y Organismos Oficiales',
	'Gerencia de Área Logística de Efectivo',
	'Gerencia de Area Mejora Continua del Servicio',
	'Gerencia de Área Mercadeo',
	'Gerencia de Área Modelo de Rentabilidad',
	'Gerencia de Area Negocios Fiduciarios',
	'Gerencia de Área Negocios Tecnología',
	'Gerencia de Area Servicios',
	'Gerencia de Area Oficina de Proyectos',
	'V.P. Corporativa Bei Sector Agropecuario',
	'Gerencia de Area Operaciones de Seguridad',
	'Gerencia de Área Operaciones de Tesorería',
	'Gerencia de Área Operaciones Especializadas',
	'Gerencia de Área Proyectos de Desarrollo Sostenible',
	'Gerencia de Área Pagos de Servicios Públicos',
	'Gerencia de Área Personas y Cultura',
	'Gerencia de Area Plan Mayor',
	'Gerencia de Area Plataforma Especializada',
	'Gerencia de Área Prev y Control de Lc-ft-fpadm',
	'Gerencia de Área Procesos Especiales y  Reportería',
	'Gerencia de Area Producción',
	'Gerencia de Área Productos y Serv Tdd',
	'Gerencia de Área Productos y Servicios Tdc',
	'V.P. Control de Inmuebles',
	'Gcia. de Credito Banca Especializada',
	'Gerencia de Área Proyectos Bi y Regulatorios',
	'Gerencia de Area Proyectos Canales Digitales',
	'Gerencia de Area Proyectos Core Bancario',
	'Gerencia de Area Proyectos de Seguridad Ti',
	'Gerencia de Área Proyectos Integraci de Plataforma',
	'V.P. Eficiencia Comercial',
	'Gerencia de Área Proyectos Pos y Atm',
	'Gerencia de Creación de Usuarios',
	'Gerencia de Área Recauda de Impuestos y Otros Serv',
	'Gerencia de Área Reclamos de Canales Electronicos',
	'Gcia. Regional de Negocios Sector Público Centro',
	'Gerencia de Área Sector Financiero',
	'Gerencia de Area Seguridad en Aplicaciones y Datos',
	'Gerencia de Area Seguridad en Infraestructura y Perímetro',
	'Gerencia de Area Seguridad Industrial y Contingenc',
	'Gerencia de Área Seguridad Preventiva y Prot. Física',
	'Gerencia de Area Sistema de Medios de Pago',
	'Gerencia de Área Soporte de Atms',
	'Gerencia de Area Transformación',
	'Gerencia de Area Valores y Accionistas',
	'Gerencia de Atención de Organismos Oficiales',
	'Gerencia de Caja de Ahorros',
	'V.P. Procura, Almacén y Servicios Generales',
	'Coordinación Cont. Operativo de Centros de Acopio',
	'Gerencia de Canales y Procesos Contables',
	'Gerencia de Certificación',
	'V.P. Seguridad de la Informacion',
	'Gerencia de Compensación Salarial',
	'Gerencia de Control de Activos y Gastos',
	'Gerencia de Control de Cambios',
	'Gerencia de Control de Cartera de Credito',
	'Gerencia de Control y Gestión',
	'Gerencia de Departamento Soporte Regulatorio',
	'Gerencia de Detección de Amenazas',
	'Gerencia de Distribución',
	'Gerencia de Fianzas, Garantias y Cartas Crédito',
	'Gerencia de Gestión de Identidades',
	'Gerencia de Gestión de Nomina',
	'Gerencia de Gestión de Procesos',
	'Gerencia de Gobierno Corporativo',
	'Gerencia de Area Tributos',
	'Gerencia de Integración Plataforma As-400',
	'Gerencia de Inteligencia de Negocio',
	'Gerencia de Investigaciones',
	'Gerencia de Mecanismos Cambiarios',
	'Gerencia de Mercado Monetario',
	'Gerencia de Metodología de Riesgo Financiero',
	'Gerencia de Mod. de Inf. Finan. y Presupuestaria',
	'Gerencia de Monitoreo Telco E Infraestructura',
	'Gerencia de Ara de Contraloría de Datos',
	'Gerencia de Monitoreo y Seg. Sobre Cont. de Neg',
	'Gerencia de Monitoreo y Verificación de Op Inusual',
	'Gerencia de Negocios Apoyo A la Presidencia',
	'Gerencia de Negocios Aragua',
	'V.P. de Negocios Zona Ib',
	'Gerencia de Negocios Capital I',
	'Gerencia de Area Proyectos Pos Atms',
	'Gerencia de Negocios Capital I',
	'Gerencia de Área Ctrol Institucional y Asuntos Corp.',
	'Gerencia de Negocios Capital II',
	'Gerencia de Negocios Capital II',
	'Gerencia de Negocios Capital III',
	'Gerencia de Area de Negocios Sector Financiero',
	'Gerencia de Negocios Consumo',
	'V.P. Zona Aragua',
	'Gerencia de Negocios Fiduciarios',
	'Gerencia de Negocios Gas y Petróleo',
	'Gerencia de Negocios I',
	'Gerencia de Negocios II',
	'Gerencia de Negocios los Andes',
	'Gerencia de Negocios Manufactura',
	'Gerencia de Negocios Manufactura y Consumo I',
	'Gerencia de Negocios Manufactura y Consumo II',
	'Gerencia de Negocios Manufactura y Consumo III',
	'Gerencia de Negocios Occidente',
	'Gerencia de Negocios Occidente',
	'Gerencia de Negocios Oriente',
	'Gerencia de Negocios Oriente',
	'Gerencia de Area Proyectos Especiales',
	'Coordinacion Control y Registro de Operaciones',
	'Gerencia de Negocios Recursos',
	'Gerencia de Negocios Sector Agropecuario',
	'Gerencia de Negocios Sector Casa de Bolsa',
	'Gerencia de Negocios Sector Seguros',
	'Gerencia de Negocios Servicios I',
	'Gerencia de Negocios Servicios II',
	'Gerencia de Negocios Servicios III',
	'Gerencia de Políticas, Norma y Estándares',
	'Gerencia de Presupuesto',
	'Gerencia de Producción Caracas',
	'Gerencia de Producción Tdc',
	'Gerencia de Proyectos y Soporte Tecnico',
	'Gerencia de Renta Fija',
	'Gerencia de Riesgo de Credito',
	'Gerencia de Riesgo de Mercado y Liquidez',
	'Gerencia de Riesgo Operacional Mid y Back Office',
	'Gerencia de Riesgo y Cultura',
	'Gerencia de Seguridad Perimetral',
	'Gerencia de Seguridad y Salud Laboral',
	'Gerencia de Selección de Personal',
	'Gerencia de Activos Fijos',
	'Gerencia de Servicios Post Venta Jurídico',
	'Gerencia de Sistemas de Sucursales',
	'V.P. Gestión de Soporte Técnico y Arquitectura Ti',
	'Gerencia de Sistemas Pos',
	'Gerencia de Negocios (bei) III',
	'Gerencia de Sistemas Productos Activos-pasivos',
	'Gerencia de Soporte Tecnico Caracas',
	'Gerencia de Soporte Tecnico Occidente',
	'Gerencia de Validacion y Crédito',
	'Gerencia de Zona Andes I',
	'Gerencia de Zona Andes II',
	'Gerencia de Zona Carabobo I',
	'Gerencia de Zona Carabobo II',
	'Gerencia de Zona Falcón',
	'Gerencia Regional de Negocios Sector Agropecuario',
	'Gerencia de Zona Insular',
	'Gerencia de Zona Oriente Norte I',
	'Gerencia de Zona Oriente Norte II',
	'Gerencia de Zona Oriente Norte III',
	'Gerencia de Zona Oriente Sur',
	'Gerencia de Monitoreo y Verificación de Op. Inusual',
	'Gerencia de Zona Zulia I',
	'V.P. Corporativa Bei Sector Financiero',
	'Gerencia de Zona Zulia II',
	'Gerencia Desarrollo de Aplicaciones Internas',
	'Gerencia Distribución Tdc',
	'Gerencia Documentación de Activos',
	'Gerencia Documentación y Soporte de Aplicaciones',
	'Gerencia Eficiencia Comercial',
	'Gerencia Emisión Tdc',
	'Gerencia Energía Caracas',
	'Gerencia Energía Maracaibo',
	'Gerencia Estadística Sobre Metodología de Riesgo',
	'Gerencia Estadística y Mantenimiento de Registros',
	'Gerencia Gestión de Información',
	'Gerencia Gestión de Presupuesto Ti',
	'Gerencia Gestión Documental',
	'Gerencia Información Financiera',
	'Gerencia de Área Gestión y Control Operativo',
	'Gerencia Integración A Terceros',
	'Gerencia Integración de Plataformas Distribuidas',
	'V.P. de Banca Internacional',
	'Gerencia Investigación Económica',
	'Gerencia Legal',
	'Gerencia Monitoreo Atm',
	'Gerencia de Área Productos y Serv Tdd y Sol Emerg',
	'Gerencia Monitoreo y Anti Fraude Capital',
	'Gerencia Monitoreo y Anti Fraude Occidente',
	'Gerencia Nacional de Consola',
	'Gerencia Open Banking',
	'Gerencia Operaciones Especializadas',
	'V.P. Desarrollo de Sotware',
	'Gerencia de Area Bi y Sistemas Regulatorios',
	'Gerencia Operaciones Moneda Extranjera',
	'V.P. Apoyo A la Presidencia',
	'Gerencia Operaciones Moneda Nacional',
	'Gerencia Plataforma Media',
	'Gerencia Prueba de Software',
	'Gerencia Reclamos de Canales Electronicos Zona 1',
	'Gerencia Reclamos de Canales Electronicos Zona 2',
	'Gerencia Redes y Comunicación',
	'Gerencia Regional Operacion de Agencias Capital',
	'Gerencia Regional Operacion de Agencias Carabobo',
	'Gerencia Regional Operación de Agencias Centro Occidente',
	'Gerencia Regional Operacion de Agencias Guayana',
	'Gerencia Regional Operacion de Agencias los Andes',
	'Gerencia Regional Operacion de Agencias Occidente',
	'Gerencia Regional Operacion de Agencias Oriente',
	'Gerencia de Area Ctrl Contable y Gestión de Gasto',
	'Gcia. de Área de Proyectos de Transformación',
	'Gerencia de Área Estadist y Análisis Estratégico',
	'Gerencia Riesgo Operacional Front Office',
	'Gerencia Salud Ocupacional',
	'Gerencia de Seguridad As-400',
	'Gerencia de Validacion',
	'Gerencia Seguimiento y Control',
	'Gerencia de Area Gestión de Certificación',
	'Gerencia Servicio Al Cliente y Recuperaciones Pos',
	'Gerencia Soporte Inv. Tecno. de Seguridad Bancaria',
	'Gerencia Soporte Pos Occidente',
	'Gerencia Soporte Pos-capital-centro',
	'Gerencia Técnica Atm',
	'Gerencia Telefonía',
	'Gerencia Zona Centro Occidente Zona Occidente I',
	'Grerncia de Area Seguridad Informática',
	'Junta Directiva',
	'Presidencia',
	'Presidencia Ejecutiva',
	'Secretaria de la Junta Directiva',
	'Tesoreria',
	'V.P. Planificación Estratégica y Pmo',
	'Unidad Admon Integral de Riesgos',
	'Gerencia de Control Presupuestario',
	'V.P. Análisis de Crédito',
	'V.P. Arquitectura y Contingencia',
	'V.P. Aseguramiento Normativo',
	'V.P. Asuntos Legales',
	'V.P. Atención Al Cliente',
	'V.P. Banca Privada',
	'V.P. Bei',
	'V.P. Calidad de Servicio',
	'V.P. Contratos, Servicios y Pagos',
	'V.P. Corporativa Sector Agropecuario',
	'V.P. Corporativa Sector Financiero',
	'V.P. Corporativa Sector Manufactura y Consumo',
	'V.P. Corporativa Sector Servicios',
	'V.P. Cumplimiento y Control de Gestión',
	'V.P. de Contraloría',
	'V.P. de Corresponsalia',
	'V.P. de Fideicomiso',
	'V.P. de Liquidaciones y Servicios',
	'V.P. de Mercadeo y Comunicaciones Corporativas',
	'V.P. de Negocios Zona I',
	'V.P. de Negocios Zona I',
	'V.P. de Negocios Zona II',
	'V.P. de Negocios Zona III',
	'Gerencia Proyecto Especial Control y Gestión',
	'V.P. de Productos y Servicios de Tarjetas',
	'V.P. de Recursos Humanos y Cultura Organizacional',
	'V.P. de Zona Aragua I',
	'V.P. de Zona Aragua II',
	'V.P. de Zona I Administracion de Agencias I',
	'V.P. de Zona II Administracion de Agencias II',
	'V.P. Desarrollo de Negocios E Innovación',
	'V.P. Desarrollo de Software Canales Digitales',
	'V.P. Desarrollo de Software Core Bancario',
	'V.P.E. Banca Especializada',
	'V.P. Desarrollo y Gestión Comercial',
	'V.P. Emisión y Distribución',
	'V.P. Emprendimientos',
	'V.P. de Negocios Zona Iib',
	'V.P. Energía',
	'V.P. Gestión de Activos',
	'Gerencia de Area de Soporte de Atms',
	'V.P. Gestion de Contabilidad Pagos y Tributos',
	'V.P. Bei IV',
	'V.P. Gestión de Proyectos Ti',
	'Gerencia de Administración Plataforma Media',
	'Gerencia de Area de Negocios Corporativa Centro',
	'V.P. Gestión de Seguridad Bancaria',
	'Gerencia de Area Seleccion de Talento',
	'V.P. Gestión Organizacional y Procesos',
	'Gerencia de Area de Negocios Corporativa II',
	'V.P. Infraestructura y Mantenimiento Fisico',
	'V.P. Inteligencia de Negocios y Analítica Digital',
	'V.P. Oficial de Seguridad de la Información (ciso)',
	'V.P. Operaciones de Efectivo',
	'Gerencia de Negocios Carabobo I',
	'V.P. Operaciones de Tesorería',
	'V.P. Planificación Estratégica Pmo',
	'V.P. Planificación Financiera y Presupuesto',
	'V.P. Prevención del Fraude',
	'Gerencia Control y Seguimiento (bei)',
	'V.P. Procura y Servicios Generales',
	'V.P. Región Aragua - los Llanos',
	'V.P. Región Centro Occidente',
	'V.P. Región Occidente',
	'V.P. Región Oriente',
	'V.P. Regional Administración de Agencias',
	'V.P. Regional Región Capital I',
	'V.P. Regional Región Capital II',
	'V.P. Seguimiento y Control de Credito',
	'Gerencia de Area Admin. de Inmuebles Propios',
	'V.P. Seguridad Preventiva y Protección Física',
	'V.P. Servicios Al Cliente',
	'V.P. Soluciones Electrónicas',
	'V.P. Soporte A Canales Electrónicos',
	'V.P. Tecnología',
	'V.P. Upclcftfpadm',
	'V.P. Zona Carabobo',
	'V.P. Zona Centro Occidente',
	'V.P. Desarollo de Negocios E Innovación',
	'V.P. Zona Insular',
	'V.P. Zona los Andes',
	'V.P. Zona los Llanos',
	'V.P. Zona Oriente',
	'V.P. Zona Zulia Falcón',
	'V.P.E. Banca Corporativa Multinacional & Energía',
	'V.P.E. Banca Corporativa Nacional',
	'V.P.E. Cumplimiento',
	'V.P.E. de Banca Comercial',
	'V.P.E. Desarrollo Organizacional y Transformación',
	'V.P.E. Finanzas',
	'V.P.E. Gestión del Riesgo',
	'V.P.E. Ingenieria Tecnológica',
	'Gerencia de Fianzas y Garantias',
	'V.P.E. Operaciones y Administración',
	'V.P.E. Seguridad Corporativa y Prevención del Frau',
	'V.P.E. Servicios Jurídicos',
	'V.P.E. Soluciones de Clientes y Serv. Digitales'
]

module.exports = { unidadList }
