const { VPEData, VPEOnlyNames } = require('./area/vicepresidenciaEjecutiva')
const { cargoOnlyNames, cargosData } = require('./cargo/cargos')

function capitalCadena(cadena) {
	return cadena
		.toLowerCase()
		.split('. ')
		.map(text =>
			text
				.split(' ')
				.map(palabra => palabra.charAt(0).toUpperCase() + palabra.slice(1))
				.join(' ')
		)
		.join('. ')
}

const presidenciaEmployee = [
	{
		userName: 'kdelvillar'.toLowerCase(),
		name: capitalCadena('KATIUSKA LUCILA'),
		lastName: capitalCadena('DEL VILLAR ARAUJO'),
		type: 'regular',
		email: 'kdelvillar@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 11255,
		nationality: 'V'.toUpperCase(),
		cedula: 10401340,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['AUDITOR INTERNO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'llinares'.toLowerCase(),
		name: capitalCadena('LUIS EDUARDO'),
		lastName: capitalCadena('LINAREZ GAMEZ'),
		type: 'regular',
		email: 'llinares@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 2296,
		nationality: 'V'.toUpperCase(),
		cedula: 12692060,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['DEFENSORIA DEL CLIENTE'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['COORDINADOR(A)'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'mabuitrago'.toLowerCase(),
		name: capitalCadena('MARIA ELENA'),
		lastName: capitalCadena('BUITRAGO CARRIAZO'),
		type: 'regular',
		email: 'mabuitrago@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 3987,
		nationality: 'V'.toUpperCase(),
		cedula: 5139486,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['DEFENSORIA DEL CLIENTE'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['DEFENSOR DEL CLIENTE'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'scioffi'.toLowerCase(),
		name: capitalCadena('SARAHI BETZABETH'),
		lastName: capitalCadena('CIOFFI NOGALES'),
		type: 'regular',
		email: 'scioffi@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 9571,
		nationality: 'V'.toUpperCase(),
		cedula: 25517132,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['DEFENSORIA DEL CLIENTE'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ESPECIALISTA JUNIOR'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'camoreno'.toLowerCase(),
		name: capitalCadena('CARMEN CECILIA'),
		lastName: capitalCadena('MORENO ARTEAGA'),
		type: 'regular',
		email: 'camoreno@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 16335,
		nationality: 'V'.toUpperCase(),
		cedula: 24900493,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['DEFENSORIA DEL CLIENTE'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ESPECIALISTA SENIOR'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'jnogueroles'.toLowerCase(),
		name: capitalCadena('JORGE LUIS'),
		lastName: capitalCadena('NOGUEROLES GARCIA'),
		type: 'regular',
		email: 'jnogueroles@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 262,
		nationality: 'V'.toUpperCase(),
		cedula: 5967801,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['PRESIDENCIA'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['PRESIDENTE EJECUTIVO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'druiz'.toLowerCase(),
		name: capitalCadena('DELIA LUCIA'),
		lastName: capitalCadena('RUIZ SINGER'),
		type: 'regular',
		email: 'druiz@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 1050,
		nationality: 'V'.toUpperCase(),
		cedula: 6250287,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['SECRETARIA DE LA JUNTA DIRECTIVA']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['SECRETARIA JUNTA DIRECTIVA'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'gcarabali'.toLowerCase(),
		name: capitalCadena('GENESIS EYLIN'),
		lastName: capitalCadena('CARABALI RODRIGUEZ'),
		type: 'regular',
		email: 'gcarabali@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 14837,
		nationality: 'V'.toUpperCase(),
		cedula: 30291600,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['SECRETARIA DE LA JUNTA DIRECTIVA']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ASISTENTE DE DIRECCION'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'rasandoval'.toLowerCase(),
		name: capitalCadena('RAFAEL ENRIQUE'),
		lastName: capitalCadena('SANDOVAL MOYA'),
		type: 'regular',
		email: 'rasandoval@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 10994,
		nationality: 'V'.toUpperCase(),
		cedula: 10217370,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['UNIDAD ADMON INTEGRAL DE RIESGOS']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'lquero'.toLowerCase(),
		name: capitalCadena('LISMEL COROMOTO'),
		lastName: capitalCadena('QUERO BELLO'),
		type: 'regular',
		email: 'lquero@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 12735,
		nationality: 'V'.toUpperCase(),
		cedula: 14585819,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P. SEGURIDAD DE LA INFORMACION']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'jugomez'.toLowerCase(),
		name: capitalCadena('JUAN FRANCISCO'),
		lastName: capitalCadena('GOMEZ SOSA'),
		type: 'regular',
		email: 'jugomez@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 15799,
		nationality: 'V'.toUpperCase(),
		cedula: 17868843,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E FINANZAS'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'vsuarez'.toLowerCase(),
		name: capitalCadena('VICTCHELLY DEL VALLE'),
		lastName: capitalCadena('SUAREZ HERNANDEZ'),
		type: 'regular',
		email: 'vsuarez@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 15941,
		nationality: 'V'.toUpperCase(),
		cedula: 13944750,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E FINANZAS'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ASISTENTE EJECUTIVA'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'srios'.toLowerCase(),
		name: capitalCadena('SORAYA JOSEFINA'),
		lastName: capitalCadena('RIOS REGALADO'),
		type: 'regular',
		email: 'srios@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 408,
		nationality: 'V'.toUpperCase(),
		cedula: 8868325,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. BANCA CORPORATIVA EMPRESAS E INSTITUCIONES']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO DE NEGOCIOS'])[0]
			.id,
		extension: [],
		phone: []
	},
	{
		userName: 'martgonzalez'.toLowerCase(),
		name: capitalCadena('MARTHA '),
		lastName: capitalCadena('GONZALEZ MARIN'),
		type: 'regular',
		email: 'martgonzalez@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 6083,
		nationality: 'V'.toUpperCase(),
		cedula: 6075206,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. BANCA CORPORATIVA EMPRESAS E INSTITUCIONES']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ASISTENTE EJECUTIVA'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'lpulido'.toLowerCase(),
		name: capitalCadena('LOURDES DEL VALLE'),
		lastName: capitalCadena('PULIDO PINTO'),
		type: 'regular',
		email: 'lpulido@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 14151,
		nationality: 'V'.toUpperCase(),
		cedula: 11557922,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E. CUMPLIMIENTO'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['OFICIAL DE CUMPLIMIENTO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'gtrujillo'.toLowerCase(),
		name: capitalCadena('GERARDO JOSE'),
		lastName: capitalCadena('TRUJILLO ALARCON'),
		type: 'regular',
		email: 'gtrujillo@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 184,
		nationality: 'V'.toUpperCase(),
		cedula: 6818260,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E. DE BANCA COMERCIAL'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO DE NEGOCIOS'])[0]
			.id,
		extension: [],
		phone: []
	},
	{
		userName: 'iagro'.toLowerCase(),
		name: capitalCadena('INGRID COROMOTO'),
		lastName: capitalCadena('AGRO LARA'),
		type: 'regular',
		email: 'iagro@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 1236,
		nationality: 'V'.toUpperCase(),
		cedula: 11413982,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E. DE BANCA COMERCIAL'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ASISTENTE EJECUTIVA'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'abaptista'.toLowerCase(),
		name: capitalCadena('ANDREA ALEJANDRA'),
		lastName: capitalCadena('BAPTISTA PEÑA'),
		type: 'regular',
		email: 'abaptista@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 14836,
		nationality: 'V'.toUpperCase(),
		cedula: 31415719,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. DESARROLLO ORGANIZACIONAL Y TRANSFORMACIÓN']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ASISTENTE EJECUTIVA'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'kadiaz'.toLowerCase(),
		name: capitalCadena('KARINA '),
		lastName: capitalCadena('DIAZ MATOS'),
		type: 'regular',
		email: 'kadiaz@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 15953,
		nationality: 'V'.toUpperCase(),
		cedula: 12386062,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. DESARROLLO ORGANIZACIONAL Y TRANSFORMACIÓN']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'carodriguez'.toLowerCase(),
		name: capitalCadena('CARLOS FERECIDES'),
		lastName: capitalCadena('RODRIGUEZ BASTIDAS'),
		type: 'regular',
		email: 'carodriguez@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 15358,
		nationality: 'V'.toUpperCase(),
		cedula: 10674341,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. GESTIÓN DE LA SEGURIDAD Y PREVENCIÓN']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'dlopez'.toLowerCase(),
		name: capitalCadena('DELVALLE VIDALIA'),
		lastName: capitalCadena('LOPEZ DE MEDINA'),
		type: 'regular',
		email: 'dlopez@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 15743,
		nationality: 'V'.toUpperCase(),
		cedula: 11970289,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. GESTIÓN DE LA SEGURIDAD Y PREVENCIÓN']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ASISTENTE EJECUTIVA'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'fraperez'.toLowerCase(),
		name: capitalCadena('FRANK RAFAEL'),
		lastName: capitalCadena('PEREZ MILLAN'),
		type: 'regular',
		email: 'fraperez@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 5299,
		nationality: 'V'.toUpperCase(),
		cedula: 6393312,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E. GESTIÓN DEL RIESGO'])[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'cmendoza'.toLowerCase(),
		name: capitalCadena('CARLOS ENRIQUE'),
		lastName: capitalCadena('MENDOZA PARRA'),
		type: 'regular',
		email: 'cmendoza@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 265,
		nationality: 'V'.toUpperCase(),
		cedula: 4568285,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E. INGENIERIA TECNOLÓGICA'])[0]
			.id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ESPECIALISTA JUNIOR'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'rcastaneda'.toLowerCase(),
		name: capitalCadena('ROBERTO RAFAEL'),
		lastName: capitalCadena('CASTAÑEDA PERALTA'),
		type: 'regular',
		email: 'rcastaneda@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 7254,
		nationality: 'V'.toUpperCase(),
		cedula: 5891127,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E. INGENIERIA TECNOLÓGICA'])[0]
			.id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'lemoreno'.toLowerCase(),
		name: capitalCadena('LEONARDO JOSE'),
		lastName: capitalCadena('MORENO GONZALEZ'),
		type: 'regular',
		email: 'lemoreno@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 2019,
		nationality: 'V'.toUpperCase(),
		cedula: 12417338,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. OPERACIONES CENTRALIZADAS']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'sguerra'.toLowerCase(),
		name: capitalCadena('SINAY DE LOS ANGELES'),
		lastName: capitalCadena('GUERRA VEGA'),
		type: 'regular',
		email: 'sguerra@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 15272,
		nationality: 'V'.toUpperCase(),
		cedula: 31425979,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. OPERACIONES CENTRALIZADAS']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ASISTENTE EJECUTIVA'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'jersongonzalesp@hotmail.com'.toLowerCase(),
		name: capitalCadena('JERSON JOSE'),
		lastName: capitalCadena('GONZALEZ PEREZ'),
		type: 'regular',
		email: 'jersongonzalesp@hotmail.com'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 10837,
		nationality: 'V'.toUpperCase(),
		cedula: 14286171,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['V.P.E. SERVICIOS JURÍDICOS'])[0]
			.id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['MENSAJERO EXTERNO'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'jeahernandez'.toLowerCase(),
		name: capitalCadena('JEANKERLIS DANIELA'),
		lastName: capitalCadena('HERNANDEZ PEÑA'),
		type: 'regular',
		email: 'jeahernandez@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 14845,
		nationality: 'V'.toUpperCase(),
		cedula: 31255813,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. SOLUCIONES DE CLIENTES Y SERV. DIGITALES']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['ASISTENTE EJECUTIVA'])[0].id,
		extension: [],
		phone: []
	},
	{
		userName: 'mcabrera'.toLowerCase(),
		name: capitalCadena('MARIELA '),
		lastName: capitalCadena('CABRERA GONZALEZ'),
		type: 'regular',
		email: 'mcabrera@bnc.com.ve'.toLowerCase(),
		isStillWorking: true,
		employeeCode: 15946,
		nationality: 'V'.toUpperCase(),
		cedula: 6322092,
		locationId: null,
		directivaId: VPEData.filter(vpe => vpe.name === VPEOnlyNames['AUDITORIA INTERNA'])[0].directivaId,
		vicepresidenciaEjecutivaId: VPEData.filter(
			vpe => vpe.name === VPEOnlyNames['V.P.E. SOLUCIONES DE CLIENTES Y SERV. DIGITALES']
		)[0].id,
		vicepresidenciaId: null,
		departamentoId: null,
		cargoId: cargosData.filter(cargo => cargo.name === cargoOnlyNames['VICEPRESIDENTE EJECUTIVO'])[0].id,
		extension: [],
		phone: []
	}
]
module.exports = { presidenciaEmployee }
