export enum SettingsKeys {
	DEFAULT_PASSWORD_HASH = 'DEFAULT_PASSWORD_HASH',
	PASSWORD_EXPIRY_DAYS = 'PASSWORD_EXPIRY_DAYS',
	FAILED_ATTEMPTS_LIMIT = 'FAILED_ATTEMPTS_LIMIT',
	LOCKOUT_UNTIL_MINUTES = 'LOCKOUT_UNTIL_MINUTES',
	LOCATION_MONITORING_ENABLED = 'LOCATION_MONITORING_ENABLED',
	LOCATION_MONITORING_CONCURRENCY_LIMIT = 'LOCATION_MONITORING_CONCURRENCY_LIMIT',
	LOCATION_MONITORING_IDLE_TIME_MINUTES = 'LOCATION_MONITORING_IDLE_TIME_MINUTES',
	LOCATION_MONITORING_START_HOUR = 'LOCATION_MONITORING_START_HOUR',
	LOCATION_MONITORING_END_HOUR = 'LOCATION_MONITORING_END_HOUR',
	LOCATION_MONITORING_START_DAY_OF_WEEK = 'LOCATION_MONITORING_START_DAY_OF_WEEK',
	LOCATION_MONITORING_END_DAY_OF_WEEK = 'LOCATION_MONITORING_END_DAY_OF_WEEK',
	LOCATION_MONITORING_DISABLE_TIME_CHECKS = 'LOCATION_MONITORING_DISABLE_TIME_CHECKS',
	DEVICE_MONITORING_ENABLED = 'DEVICE_MONITORING_ENABLED',
	DEVICE_MONITORING_CONCURRENCY_LIMIT = 'DEVICE_MONITORING_CONCURRENCY_LIMIT',
	DEVICE_MONITORING_IDLE_TIME_MINUTES = 'DEVICE_MONITORING_IDLE_TIME_MINUTES',
	DEVICE_MONITORING_START_HOUR = 'DEVICE_MONITORING_START_HOUR',
	DEVICE_MONITORING_END_HOUR = 'DEVICE_MONITORING_END_HOUR',
	DEVICE_MONITORING_START_DAY_OF_WEEK = 'DEVICE_MONITORING_START_DAY_OF_WEEK',
	DEVICE_MONITORING_END_DAY_OF_WEEK = 'DEVICE_MONITORING_END_DAY_OF_WEEK',
	DEVICE_MONITORING_DISABLE_TIME_CHECKS = 'DEVICE_MONITORING_DISABLE_TIME_CHECKS'
}

/**
 * @description Define todas las claves (keys) de configuración utilizadas en la aplicación.
 * Este objeto se utiliza para obtener tipado estricto (string literals)
 * y actúa como la fuente única de verdad para los nombres de las claves en la DB.
 */
export const AppSettingKeys = {
	SECURITY: {
		DEFAULT_PASSWORD_HASH: 'DEFAULT_PASSWORD_HASH',
		PASSWORD_EXPIRY_DAYS: 'PASSWORD_EXPIRY_DAYS',
		FAILED_ATTEMPTS_LIMIT: 'FAILED_ATTEMPTS_LIMIT',
		LOCKOUT_UNTIL_MINUTES: 'LOCKOUT_UNTIL_MINUTES',
		ALLOWED_EMAIL_DOMAINS: 'ALLOWED_EMAIL_DOMAINS'
	} as const,

	LOCATION_MONITORING: {
		ENABLED: 'LOCATION_MONITORING_ENABLED',
		CONCURRENCY_LIMIT: 'LOCATION_MONITORING_CONCURRENCY_LIMIT',
		IDLE_TIME_MINUTES: 'LOCATION_MONITORING_IDLE_TIME_MINUTES',
		START_HOUR: 'LOCATION_MONITORING_START_HOUR',
		END_HOUR: 'LOCATION_MONITORING_END_HOUR',
		START_DAY_OF_WEEK: 'LOCATION_MONITORING_START_DAY_OF_WEEK',
		END_DAY_OF_WEEK: 'LOCATION_MONITORING_END_DAY_OF_WEEK',
		DISABLE_TIME_CHECKS: 'LOCATION_MONITORING_DISABLE_TIME_CHECKS'
	} as const,

	DEVICE_MONITORING: {
		ENABLED: 'DEVICE_MONITORING_ENABLED',
		CONCURRENCY_LIMIT: 'DEVICE_MONITORING_CONCURRENCY_LIMIT',
		IDLE_TIME_MINUTES: 'DEVICE_MONITORING_IDLE_TIME_MINUTES',
		START_HOUR: 'DEVICE_MONITORING_START_HOUR',
		END_HOUR: 'DEVICE_MONITORING_END_HOUR',
		START_DAY_OF_WEEK: 'DEVICE_MONITORING_START_DAY_OF_WEEK',
		END_DAY_OF_WEEK: 'DEVICE_MONITORING_END_DAY_OF_WEEK',
		DISABLE_TIME_CHECKS: 'DEVICE_MONITORING_DISABLE_TIME_CHECKS'
	} as const
} as const

/**
 * @description Exporta un tipo de utilidad para referenciar cualquier clave válida.
 */
export type SettingKeyName =
	| (typeof AppSettingKeys.SECURITY)[keyof typeof AppSettingKeys.SECURITY]
	| (typeof AppSettingKeys.LOCATION_MONITORING)[keyof typeof AppSettingKeys.LOCATION_MONITORING]
	| (typeof AppSettingKeys.DEVICE_MONITORING)[keyof typeof AppSettingKeys.DEVICE_MONITORING]

/**
 * @description Define los valores por defecto para las configuraciones de la aplicación.
 * Esta estructura coincide con AppSettingKeys para mantener la coherencia.
 */
export const AppSettingDefaults = {
	SECURITY: {
		PASSWORD_EXPIRY_DAYS: 90,
		FAILED_ATTEMPTS_LIMIT: 5,
		LOCKOUT_UNTIL_MINUTES: 15
	},

	LOCATION_MONITORING: {
		ENABLED: false,
		CONCURRENCY_LIMIT: 5,
		IDLE_TIME_MINUTES: 5,
		START_HOUR: 8,
		END_HOUR: 18,
		START_DAY_OF_WEEK: 1, // Lunes
		END_DAY_OF_WEEK: 5, // Viernes
		DISABLE_TIME_CHECKS: false
	},

	DEVICE_MONITORING: {
		ENABLED: false,
		CONCURRENCY_LIMIT: 5,
		IDLE_TIME_MINUTES: 5,
		START_HOUR: 8,
		END_HOUR: 18,
		START_DAY_OF_WEEK: 1, // Lunes
		END_DAY_OF_WEEK: 5, // Viernes
		DISABLE_TIME_CHECKS: false
	}
} as const
