const categoryOnlyNames = {
	COMPUTADORAS: 'Computadoras',
	SERVIDORES: 'Servidores',
	LAPTOPS: 'Laptops',
	ALLINONE: 'All in One',
	MONITORES: 'Monitores',
	IMPRESORASFINANCIERAS: 'Impresoras Financieras',
	IMPRESORASLASER: 'Impresoras Laser',
	IMPRESORASTINTA: 'Impresoras Tinta',
	DISCOSDUROS: 'Discos Duros',
	TECLADOS: 'Teclados',
	MOUSE: 'Mouses',
	BAM: 'BAMs',
	MFP: 'Impresoras Multifuncionales',
	PHONE: 'Celulares',
	SCANNER: 'Escaners',
	ANTENAS: 'Antenas',
	CABLEUSB: 'Cable USB',
	CAMARAS: 'Camaras',
	WEBCAM: 'WebCam',
	IPAD: 'IPAD',
	CORNETAS: 'Cornetas',
	DOCKING: 'Docking',
	LAPIZOPTICO: 'Lapiz Optico',
	CONVERTIDORVGAHDMI: 'Convertidor de VGA - HDMI',
	MIC: 'Micrófono'
}

const categoryData = [
	{ id: '1', name: 'Computadoras' },
	{ id: '2', name: 'Servidores' },
	{ id: '3', name: 'Laptops' },
	{ id: '4', name: 'All in One' },
	{ id: '5', name: 'Monitores' },
	{ id: '6', name: 'Impresoras Financieras' },
	{ id: '7', name: 'Impresoras Laser' },
	{ id: '8', name: 'Impresoras Tinta' },
	{ id: '9', name: 'Discos Duros' },
	{ id: '10', name: 'Teclados' },
	{ id: '11', name: 'Mouses' },
	{ id: '12', name: 'BAMs' },
	{ id: '13', name: 'Impresoras Multifuncionales' },
	{ id: '14', name: 'Celulares' },
	{ id: '15', name: 'Escaners' },
	{ id: '16', name: 'Antenas' },
	{ id: '17', name: 'Cable USB' },
	{ id: '18', name: 'Camaras' },
	{ id: '19', name: 'IPAD' },
	{ id: '20', name: 'WebCam' },
	{ id: '21', name: 'Cornetas' },
	{ id: '22', name: 'Docking' },
	{ id: '23', name: 'Lapiz Optico' },
	{ id: '24', name: 'Convertidor de VGA - HDMI' },
	{ id: '25', name: 'Micrófono' }
]

module.exports = { categoryData, categoryOnlyNames }
