const categoryOnlyNames = {
	COMPUTADORAS: '1',
	SERVIDORES: '2',
	LAPTOPS: '3',
	ALLINONE: '4',
	MONITORES: '5',
	IMPRESORASFINANCIERAS: '6',
	IMPRESORASLASER: '7',
	IMPRESORASTINTA: '8',
	DISCOSDUROS: '9',
	TECLADOS: '10',
	MOUSE: '11',
	BAM: '12',
	MFP: '13',
	PHONE: '14',
	SCANNER: '15',
	ANTENAS: '16',
	CABLEUSB: '17',
	CAMARAS: '18',
	WEBCAM: '19',
	IPAD: '20',
	CORNETAS: '21',
	DOCKING: '22',
	LAPIZOPTICO: '23',
	CONVERTIDORVGAHDMI: '24',
	MIC: '25'
}

const categoryData = [
	{ id: '1', name: 'Computadoras' },
	{ id: '2', name: 'Servidores' },
	{ id: '3', name: 'Laptops' },
	{ id: '4', name: 'All in One' },
	{ id: '5', name: 'Monitores' },
	{ id: '6', name: 'Impresoras Financieras' },
	{ id: '7', name: 'Impresoras Laser' },
	{ id: '8', name: 'Impresoras Tinta' },
	{ id: '9', name: 'Discos Duros' },
	{ id: '10', name: 'Teclados' },
	{ id: '11', name: 'Mouses' },
	{ id: '12', name: 'BAMs' },
	{ id: '13', name: 'Impresoras Multifuncionales' },
	{ id: '14', name: 'Celulares' },
	{ id: '15', name: 'Escaners' },
	{ id: '16', name: 'Antenas' },
	{ id: '17', name: 'Cable USB' },
	{ id: '18', name: 'Camaras' },
	{ id: '19', name: 'IPAD' },
	{ id: '20', name: 'WebCam' },
	{ id: '21', name: 'Cornetas' },
	{ id: '22', name: 'Docking' },
	{ id: '23', name: 'Lapiz Optico' },
	{ id: '24', name: 'Convertidor de VGA - HDMI' },
	{ id: '25', name: 'Micrófono' }
]

module.exports = { categoryData, categoryOnlyNames }
