### obtener todas los device

GET http://localhost:5000/api/v1/devices
### obtener todas las categorias
GET http://localhost:5000/api/v1/devices/cc178070-7d92-410e-963d-0d863530a86e


### Crear un nuevo modelo HardDrive
POST http://localhost:5000/api/v1/devices
Content-Type: application/json

{
  "activo": null,
  "serial": "WCC2EAV66211",
  "statusId": 2,
  "modelId": "710a0c2a-a79f-4090-8a7c-4634b29d788e",
  "hardDriveCapacityId": 7,
  "hardDriveTypeId": 1,
  "health": 100
}
### Crear un nuevo modelo Computer
POST http://localhost:5000/api/v1/devices
Content-Type: application/json

{
  "activo": "a212520d1d",
  "serial": "aMCJ41s54d54d",
  "statusId": 2,
  "modelId": "83c38f9b-a0ac-4350-9204-886ea8e4e967",
  "processorId": "a267cc70-f597-4e91-9330-003a89e19240",
  "memoryRamCapacity": 4096,
  "hardDriveCapacityId": 7,
  "hardDriveTypeId": 1,
  "operatingSystemId": 1,
  "operatingSystemArqId": 1,
  "ipAddress": "10.0.12.169",
  "macAddress": "00:15:5d:f8:0e:41"
}
### Crear un nuevo modelo con error
POST http://localhost:5000/api/v1/devices
Content-Type: application/json

{
  "activo": "212102",
  "serial": "MXL7005656",  
  "statusId": 2,
  "modelId": "83c38f9b-a0ac-4350-9204-886ea8e4e967"
}
### Modificar una marca con POST
PATCH  http://localhost:3000/api/v1/device/5a94384b-2e4d-4cdf-96c9-0065bf7f92a9
Content-Type: application/json

{
  "status": "Dañado"
}

