### Crear una marca con POST
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "name": "Andres",
  "lastName": "Maneiro",
  "email":"andres.mdaneiro@gmail.com",
  "password":"123456",
  "role":"Admin"
}
### Modificar una marca con POST
