services:
  Shared.Logger:
    class: ../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Shared.RedisConfig:
    class: ../../../Contexts/Shared/infrastructure/persistance/Redis/RedisRepository
    arguments: []

  Shared.SequelizeConfig:
    class: ../../../Contexts/Shared/infrastructure/persistance/Sequelize/SequelizeConfig
    arguments: []
  
  