export const codigosAreaVenezuela = [
	{ ciudad: 'Caracas', codigo: '0212', estado: 'Distrito Capital' },
	{ ciudad: 'Maracaibo', codigo: '0261', estado: 'Zulia' },
	{ ciudad: 'Valencia', codigo: '0241', estado: 'Carabobo' },
	{ ciudad: 'Barquisimeto', codigo: '0251', estado: 'Lara' },
	{ ciudad: 'Maracay', codigo: '0243', estado: 'Aragua' },
	{ ciudad: 'Ciudad Guayana', codigo: '0286', estado: 'Bolívar' },
	{ ciudad: 'Maturín', codigo: '0291', estado: 'Monagas' },
	{ ciudad: 'San Cristóbal', codigo: '0276', estado: 'Táchira' },
	{ ciudad: 'Puerto La Cruz', codigo: '0281', estado: 'Anzoátegui' },
	{ ciudad: 'Ciudad Bolívar', codigo: '0285', estado: 'Bolívar' },
	{ ciudad: 'Barinas', codigo: '0273', estado: 'Barinas' },
	{ ciudad: 'Puerto Cabello', codigo: '0242', estado: 'Carabobo' },
	{ ciudad: 'Punto Fijo', codigo: '0269', estado: 'Falcón' },
	{ ciudad: 'Mérida', codigo: '0274', estado: 'Mérida' },
	{ ciudad: 'Cabimas', codigo: '0264', estado: 'Zulia' },
	{ ciudad: 'Coro', codigo: '0268', estado: 'Falcón' },
	{ ciudad: 'Los Teques', codigo: '0212', estado: 'Miranda' },
	{ ciudad: 'Barcelona', codigo: '0281', estado: 'Anzoátegui' },
	{ ciudad: 'Trujillo', codigo: '0272', estado: 'Trujillo' },
	{ ciudad: 'Guanare', codigo: '0272', estado: 'Portuguesa' },
	{ ciudad: 'Acarigua', codigo: '0255', estado: 'Portuguesa' },
	{ ciudad: 'El Tigre', codigo: '0283', estado: 'Anzoátegui' },
	{ ciudad: 'Upata', codigo: '0288', estado: 'Bolívar' },
	{ ciudad: 'Guarenas', codigo: '0212', estado: 'Miranda' },
	{ ciudad: 'Guatire', codigo: '0212', estado: 'Miranda' },
	{ ciudad: 'Ocumare del Tuy', codigo: '0239', estado: 'Miranda' },
	{ ciudad: 'Charallave', codigo: '0239', estado: 'Miranda' },
	{ ciudad: 'Santa Teresa del Tuy', codigo: '0239', estado: 'Miranda' },
	{ ciudad: 'Cúa', codigo: '0239', estado: 'Miranda' },
	{ ciudad: 'Los Valles del Tuy', codigo: '0239', estado: 'Miranda' },
	{ ciudad: 'La Victoria', codigo: '0244', estado: 'Aragua' },
	{ ciudad: 'Turmero', codigo: '0244', estado: 'Aragua' },
	{ ciudad: 'Cagua', codigo: '0244', estado: 'Aragua' },
	{ ciudad: 'El Limón', codigo: '0243', estado: 'Aragua' },
	{ ciudad: 'Palo Negro', codigo: '0243', estado: 'Aragua' },
	{ ciudad: 'Santa Rita', codigo: '0264', estado: 'Zulia' },
	{ ciudad: 'Los Puertos de Altagracia', codigo: '0266', estado: 'Zulia' },
	{ ciudad: 'Ciudad Ojeda', codigo: '0265', estado: 'Zulia' },
	{ ciudad: 'Lagunillas', codigo: '0265', estado: 'Zulia' },
	{ ciudad: 'Santa Bárbara del Zulia', codigo: '0275', estado: 'Zulia' },
	{ ciudad: 'Machiques', codigo: '0263', estado: 'Zulia' },
	{ ciudad: 'La Fría', codigo: '0277', estado: 'Táchira' },
	{ ciudad: 'Colón', codigo: '0277', estado: 'Táchira' },
	{ ciudad: 'Táriba', codigo: '0276', estado: 'Táchira' },
	{ ciudad: 'Rubio', codigo: '0276', estado: 'Táchira' },
	{ ciudad: 'San Antonio del Táchira', codigo: '0276', estado: 'Táchira' },
	{ ciudad: 'El Vigía', codigo: '0275', estado: 'Mérida' },
	{ ciudad: 'Tovar', codigo: '0275', estado: 'Mérida' },
	{ ciudad: 'Ejido', codigo: '0274', estado: 'Mérida' },
	{ ciudad: 'El Tocuyo', codigo: '0253', estado: 'Lara' },
	{ ciudad: 'Carora', codigo: '0252', estado: 'Lara' },
	{ ciudad: 'Quíbor', codigo: '0253', estado: 'Lara' },
	{ ciudad: 'Yaritagua', codigo: '0254', estado: 'Yaracuy' },
	{ ciudad: 'Nirgua', codigo: '0254', estado: 'Yaracuy' },
	{ ciudad: 'San Felipe', codigo: '0254', estado: 'Yaracuy' },
	{ ciudad: 'Chivacoa', codigo: '0251', estado: 'Yaracuy' },
	{ ciudad: 'Guacara', codigo: '0245', estado: 'Carabobo' },
	{ ciudad: 'Mariara', codigo: '0243', estado: 'Carabobo' },
	{ ciudad: 'San Joaquín', codigo: '0245', estado: 'Carabobo' },
	{ ciudad: 'Güigüe', codigo: '0245', estado: 'Carabobo' },
	{ ciudad: 'Tinaquillo', codigo: '0258', estado: 'Cojedes' },
	{ ciudad: 'San Carlos', codigo: '0258', estado: 'Cojedes' },
	{ ciudad: 'El Baúl', codigo: '0258', estado: 'Cojedes' },
	{ ciudad: 'Valle de la Pascua', codigo: '0235', estado: 'Guárico' },
	{ ciudad: 'Altagracia de Orituco', codigo: '0238', estado: 'Guárico' },
	{ ciudad: 'San Juan de los Morros', codigo: '0246', estado: 'Guárico' },
	{ ciudad: 'Calabozo', codigo: '0246', estado: 'Guárico' },
	{ ciudad: 'Anaco', codigo: '0282', estado: 'Anzoátegui' },
	{ ciudad: 'Cantaura', codigo: '0282', estado: 'Anzoátegui' },
	{ ciudad: 'Pariaguán', codigo: '0283', estado: 'Anzoátegui' },
	{ ciudad: 'Puerto Píritu', codigo: '0259', estado: 'Anzoátegui' },
	{ ciudad: 'Clarines', codigo: '0281', estado: 'Anzoátegui' },
	{ ciudad: 'Cumaná', codigo: '0293', estado: 'Sucre' },
	{ ciudad: 'Carúpano', codigo: '0294', estado: 'Sucre' },
	{ ciudad: 'Güiria', codigo: '0294', estado: 'Sucre' },
	{ ciudad: 'Porlamar', codigo: '0295', estado: 'Nueva Esparta' },
	{ ciudad: 'Juan Griego', codigo: '0295', estado: 'Nueva Esparta' },
	{ ciudad: 'La Asunción', codigo: '0295', estado: 'Nueva Esparta' },
	{ ciudad: 'Pampatar', codigo: '0295', estado: 'Nueva Esparta' },
	{ ciudad: 'Tucupita', codigo: '0287', estado: 'Delta Amacuro' },
	{ ciudad: 'Pedernales', codigo: '0287', estado: 'Delta Amacuro' },
	{ ciudad: 'Guasdualito', codigo: '0278', estado: 'Apure' },
	{ ciudad: 'San Fernando de Apure', codigo: '0247', estado: 'Apure' },
	{ ciudad: 'Achaguas', codigo: '0247', estado: 'Apure' },
	{ ciudad: 'Elorza', codigo: '0240', estado: 'Apure' },
	{ ciudad: 'Puerto Ayacucho', codigo: '0248', estado: 'Amazonas' },
	{ ciudad: 'San Carlos de Río Negro', codigo: '0248', estado: 'Amazonas' }
]
